/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HabibiAisyahCodeRouteImport } from './routes/habibi-aisyah.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabibiAisyahCodeRoute = HabibiAisyahCodeRouteImport.update({
  id: '/habibi-aisyah/$code',
  path: '/habibi-aisyah/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/habibi-aisyah/$code': typeof HabibiAisyahCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/habibi-aisyah/$code': typeof HabibiAisyahCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/habibi-aisyah/$code': typeof HabibiAisyahCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/habibi-aisyah/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/habibi-aisyah/$code'
  id: '__root__' | '/' | '/habibi-aisyah/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HabibiAisyahCodeRoute: typeof HabibiAisyahCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habibi-aisyah/$code': {
      id: '/habibi-aisyah/$code'
      path: '/habibi-aisyah/$code'
      fullPath: '/habibi-aisyah/$code'
      preLoaderRoute: typeof HabibiAisyahCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HabibiAisyahCodeRoute: HabibiAisyahCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
