/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GaliumAiktimalCodeRouteImport } from './routes/galium-aiktimal.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaliumAiktimalCodeRoute = GaliumAiktimalCodeRouteImport.update({
  id: '/galium-aiktimal/$code',
  path: '/galium-aiktimal/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galium-aiktimal/$code': typeof GaliumAiktimalCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galium-aiktimal/$code': typeof GaliumAiktimalCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galium-aiktimal/$code': typeof GaliumAiktimalCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/galium-aiktimal/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/galium-aiktimal/$code'
  id: '__root__' | '/' | '/galium-aiktimal/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GaliumAiktimalCodeRoute: typeof GaliumAiktimalCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galium-aiktimal/$code': {
      id: '/galium-aiktimal/$code'
      path: '/galium-aiktimal/$code'
      fullPath: '/galium-aiktimal/$code'
      preLoaderRoute: typeof GaliumAiktimalCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GaliumAiktimalCodeRoute: GaliumAiktimalCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
